version: '3.7'

# starts 4 docker containers running minio server instances. Each
# minio server's web interface will be accessible on the host at port
# 9001 through 9004.
services:
    minio:
        image: 'minio/minio:latest'
        volumes:
        - data:/data
        expose:
        - "9001"
        ports:
        - "9001:9000"
        environment:
            MINIO_ACCESS_KEY: 'AKIAIOSFODNN7EXAMPLE'
            MINIO_SECRET_KEY: 'wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY'
        command: server --address 0.0.0.0:9000 /data

        healthcheck:
            test: ["CMD", "curl", "-f", "http://127.0.0.1:9000/minio/health/live"]
            interval: 30s
            timeout: 20s
            retries: 3
## For custom volumes replace with volume driver configuration.
volumes:
    data:
